# Generated by Django 4.2.4 on 2023-09-04 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='windata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_data', models.IntegerField()),
                ('max_datapoint', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
