# Generated by Django 4.2.4 on 2023-09-04 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('winapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='store_value',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('find_value', models.IntegerField()),
            ],
        ),
    ]
